spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  # JPA 설정
  jpa:
    properties:
      showSql: true
      formatSql: true
      dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddlAuto: create

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace